##basic functions

##basic

#basic

In [1]:
import numpy as np
array1=np.array([[1,2,3,4],[5,6,7,8]])
print(array1)

[[1 2 3 4]
 [5 6 7 8]]


In [2]:
array1.shape

(2, 4)

In [3]:
array1.dtype

dtype('int32')

In [4]:
np.zeros((4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [5]:
np.ones(6).dtype

dtype('float64')

In [6]:
2/array1

array([[2.        , 1.        , 0.66666667, 0.5       ],
       [0.4       , 0.33333333, 0.28571429, 0.25      ]])

##slicing

In [7]:
array2=([3,4,5,6,7,8])

In [8]:
arr=array2[4:6]

In [9]:
arr

[7, 8]

In [10]:
arr[0]=9

In [11]:
arr

[9, 8]

In [12]:
array2

[3, 4, 5, 6, 7, 8]

In [13]:
array1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [14]:
array1[0,2]

3

In [15]:
array1.sum(axis=1)

array([10, 26])

In [16]:
array2=np.array([[5,4,7,6],[9,2,3,1]])

In [17]:
array1.dot(array2.transpose())

array([[ 58,  26],
       [146,  86]])

In [18]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'Bytes0',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'Datetime64',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Str0',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'Uint64',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',

In [19]:
%%time
np.sort(array2,axis=0,kind='mergesort')

Wall time: 55.3 ms


array([[5, 2, 3, 1],
       [9, 4, 7, 6]])

In [20]:
a=np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [21]:
lspace=np.linspace(1,5,12)
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [22]:
emp=np.empty((4,6))
emp

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [23]:
emp_like=np.empty_like(lspace)
emp_like

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [24]:
ide=np.identity(45)
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [25]:
arr=np.arange(99)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [26]:
arr=arr.reshape(3,33)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [35]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [27]:
b=np.array([1,2,6,5,7,8,9,34,56,36,25,45,67,87,57,38,29,18])
b

array([ 1,  2,  6,  5,  7,  8,  9, 34, 56, 36, 25, 45, 67, 87, 57, 38, 29,
       18])

In [28]:
np.argsort(b)

array([ 0,  1,  3,  2,  4,  5,  6, 17, 10, 16,  7,  9, 15, 11,  8, 14, 12,
       13], dtype=int64)

In [29]:
np.argmin(b)

0

In [30]:
np.argmax(b)

13

In [31]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.


**array creation from other python structures

In [43]:
array1=np.array([[1,4,3,2],[8,6,5,7]])

In [44]:
array1

array([[1, 4, 3, 2],
       [8, 6, 5, 7]])

In [45]:
array1.T

array([[1, 8],
       [4, 6],
       [3, 5],
       [2, 7]])

In [46]:
for item in array1.flat:
    print(item)

1
4
3
2
8
6
5
7


In [47]:
array1.size

8

In [48]:
array1.nbytes

32

In [49]:
array1.argmin()

0

In [50]:
array1.argsort()

array([[0, 3, 2, 1],
       [2, 1, 3, 0]], dtype=int64)

In [51]:
array1.argmax(axis=0)

array([1, 1, 1, 1], dtype=int64)

In [52]:
array1.argsort(axis=1)

array([[0, 3, 2, 1],
       [2, 1, 3, 0]], dtype=int64)

In [34]:
np.array({23,43,54})

array({43, 54, 23}, dtype=object)

In [53]:
array2=np.array([[2,8,5,9],[5,4,6,2]])

In [54]:
array1+array2

array([[ 3, 12,  8, 11],
       [13, 10, 11,  9]])

In [55]:
array1*array2

array([[ 2, 32, 15, 18],
       [40, 24, 30, 14]])

In [56]:
np.sqrt(array1)

array([[1.        , 2.        , 1.73205081, 1.41421356],
       [2.82842712, 2.44948974, 2.23606798, 2.64575131]])

In [57]:
array1.sum()

36

In [59]:
array1.max()

8

In [60]:
np.where(array1>5)

(array([1, 1, 1], dtype=int64), array([0, 1, 3], dtype=int64))

In [61]:
np.count_nonzero(array1)

8

In [62]:
import sys

In [63]:
py_ar=[0,4,55,2]
np_ar=np.array(py_ar)

In [64]:
sys.getsizeof(1)*len(py_ar)

112

In [65]:
np_ar.itemsize*np_ar.size

16

In [69]:
np_ar.tolist()

[0, 4, 55, 2]